from Notes.models import File
from dotenv import load_dotenv
import os
from django.shortcuts import get_object_or_404
import requests
import tempfile
import json
import re
load_dotenv()



import google.generativeai as genai

def question_generator(pk, question_type, question_num):
    file = get_object_or_404(File, pk=pk)
    print('File object is get successfully.........')

    url = f'https://res.cloudinary.com/dly03i2co/image/upload/v1/{file.file}'

    print('URL is found successfully....')

    file_to_upload = requests.get(url).content
    """
    Here we used .content, because gemini only accepts the real file, and we can not directly save it so we need to create the temporary file of that pdf in our system.
    so .content gives us the bytes format of the data of the pdf.
    """

    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp:
        tmp.write(file_to_upload)
        tmp.flush()
        tmp_path = tmp.name

    print('File created successfully...')
    
    """
    Above is the method to store the file temporarily in the local so that we can upload it to the gemini.
    file_to_upload is a bytes as we converted it so that we can write a new file.

    tmp.flush() is used so that it cares that Make sure all bytes written in memory are saved properly to disk.
    """
    print('Making Gemini Configuration....')
    genai.configure(api_key=os.getenv('GEMINI_API_KEY'))

    model = genai.GenerativeModel("models/gemini-2.5-pro")
    """
    We are loading the model of the AI that from which ai should we talk.
    """
    print('Giving file to the gemini.....')
    file = genai.upload_file(tmp_path)

    print('Generating prompt........')

    prompt = (f'Generate {question_num} question  {question_type}.'
    'Follow the rules which are '
    'Return STRICT JSON format. '
    'IMPORTANT: Return ONLY valid JSON, no markdown formatting.'
    'In the JSON format, "```json|, ```" Do not include this type of keywords.'
    '[{'
        '"question": "string", '
        '"A": "string", '
        '"B": "string", '
        '"C": "string", '
        '"D": "string", '
        '"answer": "A|B|C|D"'
    '}] '
    'RULES '
    '1. Output ONLY numbered questions. '
    '2. DO NOT write any explanation, greetings, or commentary. '
    '3. DO NOT write "Okay", "Here are", "Sure", etc. '
    '4. Each question must start with a number. '
    '5. Each question must be on a new line. '
    '6. Output only questions. '
    '7. If you break the rules, your response is invalid.'
    '8. Question must be based on thinking.'
    '9. Do not write question number in the question'
    )

    response = model.generate_content([prompt, file])
    
    """
    The response, means question generated by the AI will not be a list or any kind of python object.
    it will be in json format, and to make that a python object we will use a load funciton of the the python.
    """

    os.remove(tmp_path)

    print('Question has been generated successfully.')
    """
    json.load(response.text)
    In return we didn't returned this because it is accept the object, for string that is generated by the ai, need to use loads.
    """
    print('Searching for this ```json|, ```.')
    if re.search('```json' ,response.text):
        print('True')
        new_text = re.sub('```json', '', response.text)
        pure_new_text =  re.sub('```', '', new_text)
        print('Removed the other text.')
    else:
        pure_new_text=response.text

    return json.loads(pure_new_text)