# Generated by Django 5.2.7 on 2025-10-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
