# Generated by Django 5.2.7 on 2025-10-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0002_streak_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='last_completed_date',
        ),
    ]
