# Generated by Django 5.2.6 on 2025-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0003_remove_streak_last_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
