# Generated by Django 5.2.7 on 2025-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0004_streak_last_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
