# Generated by Django 5.2.6 on 2025-11-28 15:37

import Notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=Notes.models.filePath),
        ),
    ]
