# Generated by Django 5.2.7 on 2025-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_ultimategoal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimategoal',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
